### ISSUE TITLE
Icons indicating direction change

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#114]
In the row of case/death/cost results, have up/down arrows between the time steps, depending on how that number has changed.

Arrow symbols here:
http://www.i2symbol.com/symbols/arrows

Red "north" arrow for big increase
Red "north east" arrow for small increase
Black "east" arrow for no change / small change (e.g. within 5%)
Green "south east" arrow for small decrease
Green "south" arrow for big decrease

**Comment by blakeelias** [comment]
Awesome!!
Could we get a slight change to this?
It'd be great to have the arrows come *in between* last round and this
round, rather than *after* the current round. For example:

*↑  28 M  →  28 M  ↗  31 M  ↓   13 M*

**Comment by sfraenkel** [comment]
Thank you,
of course, I change it.
