### ISSUE TITLE
Show some past data in the initial chart

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#117]
Show plots of daily cases all the way from Jan 2020 to Dec 2020... the player sees the history and understands the context that they're in the middle of a pandemic, not at the beginning.

If they switch their country, this graph can be different.

**Comment by felix19350** [comment]
@blakeelias How do we present this? If we start with the full year of 2020 in the graph (which is doable), how does this affect the positioning of the turn indicator and the alignment of the buttons? I'm not clear about the desired visualization for this feature and the interactions with the existing UI.

**Comment by felix19350** [comment]
@blakeelias  how does this relate to this issue: https://github.com/Pandemic-Game/pandemic-game/issues/121 ??
Are we talking about showing the data of the previous year until the start of the simulation or just the previous month?

**Comment by blakeelias** [comment]
Let's just have 1 month of previous data visualized.
As for the button alignment, that 1 month of data should have its own
column showing cases, deaths and costs for that month -- but with no
intervention buttons available for selection.

The action names would need to be moved left somewhat to accommodate this.
Does that seem reasonable?
[image: image.png]

**Comment by blakeelias** [comment]
Sorry, I forgot which issue was which.

What I said applies to #121 - and I think that's the one we should be addressing at the moment.
This one will require a bit more thought -- I'm pushing it out to the Public Beta milestone.
