### ISSUE TITLE
Spacing for player action buttons

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#23]
Should be aligned with dates on x-axis

**Comment by blakeelias** [comment]
We want everything to be fixed positioning, no responsive layout, for this version.
Some scrolling is fine (though we want it to fit on most standard laptop/desktop screen sizes, e.g. within a 1440 x 900 size)

**Comment by blakeelias** [comment]
Given fixed positioning (tables, position:absolute, etc.), should be possible to get dates of button choices to align under dates of plot axes properly, every time, no matter what device/screen/browser.

**Comment by sfraenkel** [comment]
I tested "padding:40px" for the buttons (class="row") and it works. Maybe this is easier.

**Comment by sfraenkel** [comment]
The code is now in feature-control.

**Comment by CMorenoStokoe** [comment]
@sfraenkel 
- if this is closed can you close the issue please- not sure if I need to do this? :)
- also, if so, what is the difference between your feature/controls branch compared with the feature/ui-update branch?

I want to avoid duplication and confusion here so I won't do anything just now

**Comment by sfraenkel** [comment]
@CMorenoStokoe I see the feature/ui-update for the first time, sorry, I do not know how up to date feature/controls is, so I would keep it open, till this problem is solved for a current branch.

**Comment by CMorenoStokoe** [comment]
Closing this since we agreed in last meeting that spacing does not have to be perfect
