### ISSUE TITLE
Axis labeling

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#51]
Remove axis line
Put month numbers below the graph ("month 1", "month 2", ...), but above the controls

**Comment by felix19350** [comment]
![image](https://user-images.githubusercontent.com/803668/101208293-dfd9f000-3669-11eb-8e2a-41c54602e17b.png)

**Comment by CMorenoStokoe** [comment]
Fixed to show 1/20 instead of jan etc..

**Comment by felix19350** [comment]
I would put that as "Month 1", "Month 2", etc.

**Comment by CMorenoStokoe** [comment]
I have addressed the naming of months here (named months --> numbered months), but will leave it open because @felix19350 is addressing the axis on graph

**Comment by CMorenoStokoe** [comment]
> I would put that as "Month 1", "Month 2", etc.

Oops sorry @felix19350 I didn't see your comment! Yaneer asked for 1/20 (or the American equivalent ordering- point being he asked for a number + year?) Might have misunderstood 😊 ... Also 1/20 takes 4 less characters

**Comment by CMorenoStokoe** [comment]
Looks like me and Felix have resolved this with #65 and #64 respectively, so closing this issue 👍
