### ISSUE TITLE
Highlight current step

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#52]
Highlight current button columns
Possibly highlight graph?

**Comment by blakeelias** [comment]
It would be great to see if we can add this in -- a yellow `div` overlay highlighting the choices at the current time step -- and possibly even extending up to the graph as well.

Eg as follows:
![Screenshot from 2020-12-07 11-07-10](https://user-images.githubusercontent.com/393923/101374633-66feb200-387c-11eb-9c8f-594711c72c49.png)

**Comment by blakeelias** [comment]
(Of course, the buttons still need to be selectable -- so this might require playing with the CSS `z-index` property a bit...)

**Comment by CMorenoStokoe** [comment]
Removing myself since bruno has addressed this
