### ISSUE TITLE
Button clicks don't get registered

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#63]
When you click on the button icon itself, the button clicks don't get registered, and the text of the button gets highlighted instead. This is a highly distracting bug, especially because many people will click directly on the icon itself, and won't have their click registered. 

We really can't share the game with anyone outside our team until this is fixed; it's too confusing to use right now.

**Comment by blakeelias** [comment]
I'm pretty sure @CMorenoStokoe would know how to fix this -- but perhaps @sfraenkel you could take a look as well, as I'm sure @CMorenoStokoe is busy with other UI improvements... It might be something as simple as putting a transparent `div` in front of the button text, so that the text doesn't get highlighted (assuming that's the cause of the issue; I might be wrong here)

**Comment by sfraenkel** [comment]
I belive, I had this problem before, and there is a simple way to solve it.

**Comment by CMorenoStokoe** [comment]
Fixed in feature/controls - You were previewing the main branch w/out the fix I believe. If someone can confirm we can close this? :)

**Comment by sfraenkel** [comment]
Ok thank you.

**Comment by CMorenoStokoe** [comment]
Ok, this branch seems out of date, so I will put the fix in main instead.
