### ISSUE TITLE
Distinguish this month's numbers from cumulative numbers

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#68]
Where it says "Jan 1" --> make this say "Month of January", and have it be the total number of new cases that month (i.e. 30 days' worth of cases).

For the cumulative numbers, label this as "Year-to-Date: " (under where the current label says "Jan 1"), and have it be the total number of cases.

Have the up or down arrows be relative to the last month.

**Comment by sfraenkel** [comment]
This is a good Idea
