### ISSUE TITLE
Reduce Loading time

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#69]
I haven't particularly noticed this issue, but apparently others have.

Reduce number of fonts used, etc.

**Comment by CMorenoStokoe** [comment]
Hi thanks for adding me to this, I talked to @felix19350 
about this. We can just disable extra fonts by removing the fonts from the HTML header (they will be replaced by websafe fonts which require no loading). This won't cause bugs and the fonts themselves only gave minimal graphical improvement. I am not at my computer right now but anyone could do this 😄
