### ISSUE TITLE
Graph not shown at beginning

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#70]
I think we should have at least some graph at the beginning -- even if it's empty -- like we did before.
It helps with understanding game play...

I think before, this was accomplished by having a single data point rendered on the graph, with the first day's worth of cases.

**Comment by CMorenoStokoe** [comment]
@blakeelias thanks for adding me to this. Could you possibly provide some more information please? 😄  Not sure what the problem is here, if it is about drawing the graph then I think @sfraenkel or @felix19350 would be better 😁

**Comment by blakeelias** [comment]
This may be related to a phenomenon @felix19350 observed: "If you try to go back to the first turn the graph is not correctly updated."

**Comment by CMorenoStokoe** [comment]
As much as I hate to offload work, this really sounds like something for bruno or sascha, not sure what I can do here so going to remove myself and add bruno - re-assign me here if you want me to look into it though xD

**Comment by sfraenkel** [comment]
Is this problem solved? I cannot reconstruct the bug.

**Comment by sfraenkel** [comment]
If the graph is not correctly updated, I would fix this bug.

**Comment by blakeelias** [comment]
Ah, this was actually old. It works fine now! We can close #70.
