### ISSUE TITLE
"Month of January" cases are shown before January is over

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#76]
Before the player even takes their first step, the interface says "Month of January: X cases" -- but January has not passed yet.
Once they make their choices for January, it says "Month of February: Y cases" -- but February has not passed yet either.

It should be pushed back by one time increment. I.e. you see "Month of January: Y cases", *after* January has passed.
At the initial time step, it could just say "Yesterday: X cases", to indicate this is a daily count rather than a monthly count.

**Comment by sfraenkel** [comment]
Yes, this is a problem and the cases before January will be counted in the total cases of the year. I think, we should cange it too.

**Comment by blakeelias** [comment]
Great! Yeah it's a bit tricky, just come up with anything that makes sense to you for now, and we can discuss later if we want something different; for now let's just get something that's correct and sensible.


________________________________
