### ISSUE TITLE
"Next Step" button under each turn

### ISSUE THREAD

**Issue by blakeelias** [Pandemic-Game/pandemic-game#90]
The “next step” button on the far right at the bottom is not very intuitive. Is it possible to put arrows at each time? They could be faded out except when they are pushable. 

How about just a single arrow for this?

**Comment by CMorenoStokoe** [comment]
I will try a quick hack now, making 12 buttons with the same ID. I can't think of another quick fix if this does not work, since event listener listens for `#${btn.id}` to make actions in the game engine I believe. 👍
